/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-12 06:30:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.distances;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import com.backoffice.models.Distance;
import com.backoffice.models.Lieu;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.backoffice.models.Lieu");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.backoffice.models.Distance");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Distances</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body { font-family: 'Inter', 'Segoe UI', sans-serif; background-color: #f0f4f8; min-height: 100vh; }\r\n");
      out.write("\r\n");
      out.write("        .sidebar { position: fixed; left: 0; top: 0; bottom: 0; width: 260px; background: #ffffff; border-right: 1px solid #e2e8f0; display: flex; flex-direction: column; z-index: 100; }\r\n");
      out.write("        .sidebar-brand { padding: 24px 20px; border-bottom: 1px solid #e2e8f0; display: flex; align-items: center; gap: 12px; }\r\n");
      out.write("        .sidebar-brand i { font-size: 24px; color: #1a73e8; }\r\n");
      out.write("        .sidebar-brand span { font-size: 18px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("        .sidebar-nav { padding: 16px 12px; flex: 1; }\r\n");
      out.write("        .sidebar-nav a { display: flex; align-items: center; gap: 12px; padding: 12px 16px; color: #64748b; text-decoration: none; border-radius: 8px; font-size: 14px; font-weight: 500; transition: all 0.2s; margin-bottom: 4px; }\r\n");
      out.write("        .sidebar-nav a:hover, .sidebar-nav a.active { background: #e8f0fe; color: #1a73e8; }\r\n");
      out.write("        .sidebar-nav a i { width: 20px; text-align: center; font-size: 16px; }\r\n");
      out.write("\r\n");
      out.write("        .main { margin-left: 260px; padding: 32px 40px; }\r\n");
      out.write("        .page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }\r\n");
      out.write("        .page-header h1 { font-size: 26px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("\r\n");
      out.write("        .card { background: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; margin-bottom: 20px; }\r\n");
      out.write("        .card-header { padding: 16px 20px; border-bottom: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; }\r\n");
      out.write("        .card-header h3 { font-size: 15px; font-weight: 600; color: #1e293b; display: flex; align-items: center; gap: 8px; }\r\n");
      out.write("        .card-header h3 i { color: #1a73e8; }\r\n");
      out.write("        .card-body { padding: 20px; }\r\n");
      out.write("\r\n");
      out.write("        .stats-bar { display: flex; align-items: center; gap: 8px; margin-bottom: 16px; font-size: 14px; color: #64748b; }\r\n");
      out.write("        .stats-bar strong { color: #1a73e8; font-size: 18px; }\r\n");
      out.write("\r\n");
      out.write("        /* Matrix table */\r\n");
      out.write("        .matrix-container { overflow-x: auto; }\r\n");
      out.write("        .matrix-table { width: 100%; border-collapse: collapse; font-size: 13px; }\r\n");
      out.write("        .matrix-table th, .matrix-table td { padding: 10px 12px; text-align: center; border: 1px solid #e2e8f0; }\r\n");
      out.write("        .matrix-table thead th { background: #1a73e8; color: #fff; font-weight: 600; position: sticky; top: 0; }\r\n");
      out.write("        .matrix-table thead th:first-child { background: #1557b0; }\r\n");
      out.write("        .matrix-table tbody th { background: #f8fafc; color: #1e293b; font-weight: 600; text-align: left; }\r\n");
      out.write("        .matrix-table tbody td { background: #fff; color: #334155; }\r\n");
      out.write("        .matrix-table tbody td.diagonal { background: #f1f5f9; color: #94a3b8; }\r\n");
      out.write("        .matrix-table tbody td.has-distance { background: #e8f0fe; color: #1a73e8; font-weight: 600; }\r\n");
      out.write("        .matrix-table tbody tr:hover td { background: #f0f9ff; }\r\n");
      out.write("        .matrix-table tbody tr:hover th { background: #e8f0fe; }\r\n");
      out.write("\r\n");
      out.write("        /* Légende */\r\n");
      out.write("        .legend { display: flex; gap: 24px; margin-top: 16px; font-size: 13px; color: #64748b; }\r\n");
      out.write("        .legend-item { display: flex; align-items: center; gap: 8px; }\r\n");
      out.write("        .legend-color { width: 20px; height: 20px; border-radius: 4px; border: 1px solid #e2e8f0; }\r\n");
      out.write("        .legend-color.diagonal { background: #f1f5f9; }\r\n");
      out.write("        .legend-color.has-distance { background: #e8f0fe; }\r\n");
      out.write("        .legend-color.no-distance { background: #fff; }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .sidebar { display: none; }\r\n");
      out.write("            .main { margin-left: 0; padding: 20px; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <aside class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-brand\">\r\n");
      out.write("            <i class=\"fas fa-building\"></i>\r\n");
      out.write("            <span>BackOffice ETU3341 -3256 -3326</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"sidebar-nav\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("                <i class=\"fas fa-home\"></i> Tableau de bord\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\">\r\n");
      out.write("                <i class=\"fas fa-calendar-check\"></i> Reservations\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vehicules\">\r\n");
      out.write("                <i class=\"fas fa-car\"></i> Vehicules\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotels\">\r\n");
      out.write("                <i class=\"fas fa-hotel\"></i> Hotels\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification\">\r\n");
      out.write("                <i class=\"fas fa-route\"></i> Planification\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/distances\" class=\"active\">\r\n");
      out.write("                <i class=\"fas fa-map-marked-alt\"></i> Distances\r\n");
      out.write("            </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main\">\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <h1>Distances entre les lieux</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");

            @SuppressWarnings("unchecked")
            List<Distance> distances = (List<Distance>) request.getAttribute("distances");
            @SuppressWarnings("unchecked")
            List<Lieu> lieux = (List<Lieu>) request.getAttribute("lieux");

            // Créer une matrice de distances
            Map<String, Double> matrice = new HashMap<>();
            if (distances != null) {
                for (Distance d : distances) {
                    String key = d.getLieuDepart().getId() + "_" + d.getLieuArrivee().getId();
                    matrice.put(key, d.getKm());
                }
            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("                <h3><i class=\"fas fa-map-marked-alt\"></i> Matrice des distances (en km)</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                ");
 if (lieux != null && !lieux.isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"stats-bar\">\r\n");
      out.write("                        <i class=\"fas fa-location-dot\"></i>\r\n");
      out.write("                        <strong>");
      out.print( lieux.size() );
      out.write("</strong> lieu(x) enregistré(s) |\r\n");
      out.write("                        <strong>");
      out.print( distances != null ? distances.size() : 0 );
      out.write("</strong> distance(s) définies\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"matrix-container\">\r\n");
      out.write("                        <table class=\"matrix-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>De / Vers</th>\r\n");
      out.write("                                    ");
 for (Lieu l : lieux) { 
      out.write("\r\n");
      out.write("                                        <th>");
      out.print( l.getCode() );
      out.write("</th>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                ");
 for (Lieu depart : lieux) { 
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th>");
      out.print( depart.getLibelle() );
      out.write("</th>\r\n");
      out.write("                                        ");
 for (Lieu arrivee : lieux) { 
      out.write("\r\n");
      out.write("                                            ");

                                                String key = depart.getId() + "_" + arrivee.getId();
                                                Double km = matrice.get(key);
                                                boolean isDiagonal = depart.getId().equals(arrivee.getId());
                                            
      out.write("\r\n");
      out.write("                                            ");
 if (isDiagonal) { 
      out.write("\r\n");
      out.write("                                                <td class=\"diagonal\">-</td>\r\n");
      out.write("                                            ");
 } else if (km != null) { 
      out.write("\r\n");
      out.write("                                                <td class=\"has-distance\">");
      out.print( String.format("%.1f", km) );
      out.write("</td>\r\n");
      out.write("                                            ");
 } else { 
      out.write("\r\n");
      out.write("                                                <td>-</td>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"legend\">\r\n");
      out.write("                        <div class=\"legend-item\">\r\n");
      out.write("                            <div class=\"legend-color has-distance\"></div>\r\n");
      out.write("                            <span>Distance définie</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"legend-item\">\r\n");
      out.write("                            <div class=\"legend-color diagonal\"></div>\r\n");
      out.write("                            <span>Même lieu</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"legend-item\">\r\n");
      out.write("                            <div class=\"legend-color no-distance\"></div>\r\n");
      out.write("                            <span>Non définie</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <p style=\"color: #64748b; text-align: center; padding: 40px;\">\r\n");
      out.write("                        <i class=\"fas fa-map-marker-alt\" style=\"font-size: 32px; color: #cbd5e1; display: block; margin-bottom: 12px;\"></i>\r\n");
      out.write("                        Aucun lieu enregistré\r\n");
      out.write("                    </p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
