/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-04-02 05:18:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.vehicules;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.backoffice.models.Vehicule;
import com.backoffice.models.TypeCarburant;
import java.util.List;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.backoffice.models.Vehicule");
    _jspx_imports_classes.add("com.backoffice.models.TypeCarburant");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Boolean editMode = (Boolean) request.getAttribute("editMode");
    boolean isEdit = editMode != null && editMode;
    Vehicule vehicule = (Vehicule) request.getAttribute("vehicule");
    @SuppressWarnings("unchecked")
    List<TypeCarburant> typesCarburant = (List<TypeCarburant>) request.getAttribute("typesCarburant");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>");
      out.print( isEdit ? "Modifier" : "Nouveau" );
      out.write(" vehicule</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body { font-family: 'Inter', 'Segoe UI', sans-serif; background-color: #f0f4f8; min-height: 100vh; }\r\n");
      out.write("\r\n");
      out.write("        .sidebar { position: fixed; left: 0; top: 0; bottom: 0; width: 260px; background: #ffffff; border-right: 1px solid #e2e8f0; display: flex; flex-direction: column; z-index: 100; }\r\n");
      out.write("        .sidebar-brand { padding: 24px 20px; border-bottom: 1px solid #e2e8f0; display: flex; align-items: center; gap: 12px; }\r\n");
      out.write("        .sidebar-brand i { font-size: 24px; color: #1a73e8; }\r\n");
      out.write("        .sidebar-brand span { font-size: 18px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("        .sidebar-nav { padding: 16px 12px; flex: 1; }\r\n");
      out.write("        .sidebar-nav a { display: flex; align-items: center; gap: 12px; padding: 12px 16px; color: #64748b; text-decoration: none; border-radius: 8px; font-size: 14px; font-weight: 500; transition: all 0.2s; margin-bottom: 4px; }\r\n");
      out.write("        .sidebar-nav a:hover, .sidebar-nav a.active { background: #e8f0fe; color: #1a73e8; }\r\n");
      out.write("        .sidebar-nav a i { width: 20px; text-align: center; font-size: 16px; }\r\n");
      out.write("\r\n");
      out.write("        .main { margin-left: 260px; padding: 32px 40px; }\r\n");
      out.write("        .page-header { display: flex; align-items: center; gap: 12px; margin-bottom: 28px; }\r\n");
      out.write("        .page-header h1 { font-size: 26px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("\r\n");
      out.write("        .form-card { background: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; max-width: 560px; }\r\n");
      out.write("        .form-card-header { padding: 20px 28px; border-bottom: 1px solid #e2e8f0; }\r\n");
      out.write("        .form-card-header h2 { font-size: 16px; font-weight: 600; color: #1e293b; display: flex; align-items: center; gap: 8px; }\r\n");
      out.write("        .form-card-header h2 i { color: #1a73e8; }\r\n");
      out.write("        .form-card-body { padding: 28px; }\r\n");
      out.write("\r\n");
      out.write("        .form-group { margin-bottom: 20px; }\r\n");
      out.write("        .form-group label { display: block; font-size: 13px; font-weight: 600; color: #475569; margin-bottom: 6px; }\r\n");
      out.write("        .form-control { width: 100%; padding: 10px 14px; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 14px; font-family: inherit; transition: border-color 0.2s; }\r\n");
      out.write("        .form-control:focus { outline: none; border-color: #1a73e8; box-shadow: 0 0 0 3px rgba(26,115,232,0.1); }\r\n");
      out.write("        .help-text { font-size: 12px; color: #94a3b8; margin-top: 4px; }\r\n");
      out.write("\r\n");
      out.write("        .form-actions { display: flex; gap: 12px; margin-top: 28px; padding-top: 20px; border-top: 1px solid #f1f5f9; }\r\n");
      out.write("        .btn { display: inline-flex; align-items: center; gap: 8px; padding: 10px 24px; border-radius: 8px; font-size: 14px; font-weight: 600; text-decoration: none; transition: all 0.2s; border: none; cursor: pointer; font-family: inherit; }\r\n");
      out.write("        .btn-primary { background: #1a73e8; color: #fff; }\r\n");
      out.write("        .btn-primary:hover { background: #1557b0; }\r\n");
      out.write("        .btn-secondary { background: #e2e8f0; color: #64748b; }\r\n");
      out.write("        .btn-secondary:hover { background: #cbd5e1; color: #475569; }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .sidebar { display: none; }\r\n");
      out.write("            .main { margin-left: 0; padding: 20px; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <aside class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-brand\">\r\n");
      out.write("            <i class=\"fas fa-building\"></i>\r\n");
      out.write("            <span>BackOffice ETU3341 -3256 -3326</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"sidebar-nav\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("                <i class=\"fas fa-home\"></i> Tableau de bord\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\">\r\n");
      out.write("                <i class=\"fas fa-calendar-check\"></i> Reservations\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vehicules\" class=\"active\">\r\n");
      out.write("                <i class=\"fas fa-car\"></i> Vehicules\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotels\">\r\n");
      out.write("                <i class=\"fas fa-hotel\"></i> Hotels\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification\">\r\n");
      out.write("                <i class=\"fas fa-route\"></i> Planification\r\n");
      out.write("            </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main\">\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <h1><i class=\"fas fa-car\" style=\"color:#1a73e8;\"></i> ");
      out.print( isEdit ? "Modifier le" : "Nouveau" );
      out.write(" vehicule</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-card\">\r\n");
      out.write("            <div class=\"form-card-header\">\r\n");
      out.write("                <h2><i class=\"fas fa-");
      out.print( isEdit ? "edit" : "plus-circle" );
      out.write("\"></i> ");
      out.print( isEdit ? "Modifier les informations" : "Remplir les informations" );
      out.write("</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-card-body\">\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.print( isEdit ? "vehicules/update" : "vehicules" );
      out.write("\" method=\"POST\">\r\n");
      out.write("                    ");
 if (isEdit && vehicule != null) { 
      out.write("\r\n");
      out.write("                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( vehicule.getId() );
      out.write("\"/>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"reference\"><i class=\"fas fa-tag\"></i> Reference</label>\r\n");
      out.write("                        <input type=\"text\" id=\"reference\" name=\"reference\" class=\"form-control\" required placeholder=\"ex: VH-2026-001\"\r\n");
      out.write("                               value=\"");
      out.print( isEdit && vehicule != null ? vehicule.getReference() : "" );
      out.write("\" maxlength=\"50\"/>\r\n");
      out.write("                        <p class=\"help-text\">Identifiant unique du vehicule (50 caracteres max)</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"place\"><i class=\"fas fa-chair\"></i> Nombre de places</label>\r\n");
      out.write("                        <input type=\"number\" id=\"place\" name=\"place\" class=\"form-control\" min=\"1\" max=\"50\" required placeholder=\"ex: 5\"\r\n");
      out.write("                               value=\"");
      out.print( isEdit && vehicule != null ? vehicule.getPlace() : "" );
      out.write("\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"typeCarburant\"><i class=\"fas fa-gas-pump\"></i> Type de carburant</label>\r\n");
      out.write("                        <select id=\"typeCarburant\" name=\"typeCarburant\" class=\"form-control\" required>\r\n");
      out.write("                            <option value=\"\">-- Selectionner un type --</option>\r\n");
      out.write("                            ");
 if (typesCarburant != null) {
                                for (TypeCarburant t : typesCarburant) {
                                    boolean selected = isEdit && vehicule != null && vehicule.getTypeCarburant() != null 
                                                       && vehicule.getTypeCarburant().getId().equals(t.getId());
                            
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print( t.getId() );
      out.write('"');
      out.write(' ');
      out.print( selected ? "selected" : "" );
      out.write('>');
      out.print( t.getLibelle() );
      out.write("</option>\r\n");
      out.write("                            ");
 }} 
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"vitesseMoyenne\"><i class=\"fas fa-tachometer-alt\"></i> Vitesse moyenne (km/h)</label>\r\n");
      out.write("                        <input type=\"number\" id=\"vitesseMoyenne\" name=\"vitesseMoyenne\" class=\"form-control\" min=\"1\" max=\"200\" step=\"0.01\" required placeholder=\"ex: 60\"\r\n");
      out.write("                               value=\"");
      out.print( isEdit && vehicule != null ? vehicule.getVitesseMoyenne() : "60.0" );
      out.write("\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("                        <label for=\"heureDisponibilite\"><i class=\"fas fa-clock\"></i> Heure Disponibilité (HH:MM)</label>\r\n");
      out.write("                        <input type=\"time\" id=\"heureDisponibilite\" name=\"heureDisponibilite\" class=\"form-control\"\r\n");
      out.write("                               value=\"");
      out.print( (isEdit && vehicule != null && vehicule.getHeureDisponibilite() != null) ? vehicule.getHeureDisponibilite().toString() : "00:00:00" );
      out.write("\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-actions\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                            <i class=\"fas fa-");
      out.print( isEdit ? "save" : "plus" );
      out.write("\"></i> ");
      out.print( isEdit ? "Mettre a jour" : "Creer" );
      out.write("\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vehicules\" class=\"btn btn-secondary\">\r\n");
      out.write("                            <i class=\"fas fa-times\"></i> Annuler\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
