/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-03-12 06:32:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>BackOffice - Accueil</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body { font-family: 'Inter', 'Segoe UI', sans-serif; background-color: #f0f4f8; min-height: 100vh; }\r\n");
      out.write("\r\n");
      out.write("        /* Sidebar */\r\n");
      out.write("        .sidebar { position: fixed; left: 0; top: 0; bottom: 0; width: 260px; background: #ffffff; border-right: 1px solid #e2e8f0; display: flex; flex-direction: column; z-index: 100; }\r\n");
      out.write("        .sidebar-brand { padding: 24px 20px; border-bottom: 1px solid #e2e8f0; display: flex; align-items: center; gap: 12px; }\r\n");
      out.write("        .sidebar-brand i { font-size: 24px; color: #1a73e8; }\r\n");
      out.write("        .sidebar-brand span { font-size: 18px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("        .sidebar-nav { padding: 16px 12px; flex: 1; }\r\n");
      out.write("        .sidebar-nav a { display: flex; align-items: center; gap: 12px; padding: 12px 16px; color: #64748b; text-decoration: none; border-radius: 8px; font-size: 14px; font-weight: 500; transition: all 0.2s; margin-bottom: 4px; }\r\n");
      out.write("        .sidebar-nav a:hover, .sidebar-nav a.active { background: #e8f0fe; color: #1a73e8; }\r\n");
      out.write("        .sidebar-nav a i { width: 20px; text-align: center; font-size: 16px; }\r\n");
      out.write("\r\n");
      out.write("        /* Main */\r\n");
      out.write("        .main { margin-left: 260px; padding: 32px 40px; }\r\n");
      out.write("        .page-header { margin-bottom: 32px; }\r\n");
      out.write("        .page-header h1 { font-size: 26px; font-weight: 700; color: #1e293b; margin-bottom: 4px; }\r\n");
      out.write("        .page-header p { color: #64748b; font-size: 14px; }\r\n");
      out.write("\r\n");
      out.write("        /* Module cards */\r\n");
      out.write("        .modules { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 24px; }\r\n");
      out.write("        .module-card { background: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; padding: 32px 28px; transition: all 0.25s ease; position: relative; overflow: hidden; }\r\n");
      out.write("        .module-card:hover { transform: translateY(-4px); box-shadow: 0 12px 24px rgba(26,115,232,0.12); border-color: #1a73e8; }\r\n");
      out.write("        .module-icon { width: 56px; height: 56px; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 24px; margin-bottom: 20px; }\r\n");
      out.write("        .module-icon.blue { background: #e8f0fe; color: #1a73e8; }\r\n");
      out.write("        .module-icon.green { background: #e6f4ea; color: #34a853; }\r\n");
      out.write("        .module-icon.orange { background: #fef3e2; color: #ea8600; }\r\n");
      out.write("        .module-icon.purple { background: #f3e8fd; color: #9334e6; }\r\n");
      out.write("        .module-card h2 { font-size: 18px; font-weight: 600; color: #1e293b; margin-bottom: 8px; }\r\n");
      out.write("        .module-card p { color: #64748b; font-size: 13px; line-height: 1.5; margin-bottom: 24px; }\r\n");
      out.write("        .module-card .btn { display: inline-flex; align-items: center; gap: 8px; padding: 10px 20px; background: #1a73e8; color: #ffffff; text-decoration: none; border-radius: 8px; font-size: 13px; font-weight: 600; transition: background 0.2s; }\r\n");
      out.write("        .module-card .btn:hover { background: #1557b0; }\r\n");
      out.write("        .module-card .btn i { font-size: 12px; }\r\n");
      out.write("\r\n");
      out.write("        /* Stats row */\r\n");
      out.write("        .stats-row { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 20px; margin-bottom: 32px; }\r\n");
      out.write("        .stat-card { background: #ffffff; border-radius: 10px; border: 1px solid #e2e8f0; padding: 20px 24px; }\r\n");
      out.write("        .stat-card .stat-label { font-size: 12px; color: #64748b; font-weight: 500; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }\r\n");
      out.write("        .stat-card .stat-value { font-size: 28px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .sidebar { display: none; }\r\n");
      out.write("            .main { margin-left: 0; padding: 20px; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <aside class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-brand\">\r\n");
      out.write("            <i class=\"fas fa-building\"></i>\r\n");
      out.write("            <span>BackOffice</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"sidebar-nav\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"active\">\r\n");
      out.write("                <i class=\"fas fa-home\"></i> Tableau de bord\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\">\r\n");
      out.write("                <i class=\"fas fa-calendar-check\"></i> Reservations\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vehicules\">\r\n");
      out.write("                <i class=\"fas fa-car\"></i> Vehicules\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotels\">\r\n");
      out.write("                <i class=\"fas fa-hotel\"></i> Hotels\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification\">\r\n");
      out.write("                <i class=\"fas fa-route\"></i> Planification\r\n");
      out.write("            </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main\">\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <h1>Tableau de bord</h1>\r\n");
      out.write("            <p>Bienvenue sur le BackOffice de gestion des transferts</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modules\">\r\n");
      out.write("            <div class=\"module-card\">\r\n");
      out.write("                <div class=\"module-icon blue\">\r\n");
      out.write("                    <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Reservations</h2>\r\n");
      out.write("                <p>Consulter, creer et gerer les reservations des clients pour les transferts</p>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\" class=\"btn\">\r\n");
      out.write("                    Acceder <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"module-card\">\r\n");
      out.write("                <div class=\"module-icon green\">\r\n");
      out.write("                    <i class=\"fas fa-car\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Vehicules</h2>\r\n");
      out.write("                <p>Gerer le parc de vehicules, les types de carburant et les capacites</p>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vehicules\" class=\"btn\">\r\n");
      out.write("                    Acceder <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"module-card\">\r\n");
      out.write("                <div class=\"module-icon purple\">\r\n");
      out.write("                    <i class=\"fas fa-route\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Planification</h2>\r\n");
      out.write("                <p>Generer le planning optimal des vehicules pour les transferts aeroport</p>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification\" class=\"btn\">\r\n");
      out.write("                    Acceder <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
