\c postgres;
DROP DATABASE IF EXISTS cicd;
CREATE DATABASE cicd;
\c cicd;


DROP TABLE IF EXISTS distance;
DROP TABLE IF EXISTS lieu;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS vehicule;
DROP TABLE IF EXISTS hotel cascade;
DROP TABLE IF EXISTS client;