/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-04-02 06:27:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.planification;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.backoffice.dto.RegroupementDTO;
import com.backoffice.dto.VehiculePlanningDTO;
import com.backoffice.dto.ReservationPlanningDTO;
import com.backoffice.models.Reservation;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("com.backoffice.dto.ReservationPlanningDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.backoffice.dto.VehiculePlanningDTO");
    _jspx_imports_classes.add("com.backoffice.dto.RegroupementDTO");
    _jspx_imports_classes.add("com.backoffice.models.Reservation");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Planification</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body { font-family: 'Inter', 'Segoe UI', sans-serif; background-color: #f0f4f8; min-height: 100vh; }\r\n");
      out.write("\r\n");
      out.write("        .sidebar { position: fixed; left: 0; top: 0; bottom: 0; width: 260px; background: #ffffff; border-right: 1px solid #e2e8f0; display: flex; flex-direction: column; z-index: 100; }\r\n");
      out.write("        .sidebar-brand { padding: 24px 20px; border-bottom: 1px solid #e2e8f0; display: flex; align-items: center; gap: 12px; }\r\n");
      out.write("        .sidebar-brand i { font-size: 24px; color: #1a73e8; }\r\n");
      out.write("        .sidebar-brand span { font-size: 18px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("        .sidebar-nav { padding: 16px 12px; flex: 1; }\r\n");
      out.write("        .sidebar-nav a { display: flex; align-items: center; gap: 12px; padding: 12px 16px; color: #64748b; text-decoration: none; border-radius: 8px; font-size: 14px; font-weight: 500; transition: all 0.2s; margin-bottom: 4px; }\r\n");
      out.write("        .sidebar-nav a:hover, .sidebar-nav a.active { background: #e8f0fe; color: #1a73e8; }\r\n");
      out.write("        .sidebar-nav a i { width: 20px; text-align: center; font-size: 16px; }\r\n");
      out.write("\r\n");
      out.write("        .main { margin-left: 260px; padding: 32px 40px; }\r\n");
      out.write("        .page-header { margin-bottom: 24px; }\r\n");
      out.write("        .page-header h1 { font-size: 26px; font-weight: 700; color: #1e293b; margin-bottom: 4px; }\r\n");
      out.write("        .page-header p { color: #64748b; font-size: 14px; }\r\n");
      out.write("\r\n");
      out.write("        .btn { display: inline-flex; align-items: center; gap: 8px; padding: 10px 20px; border-radius: 8px; font-size: 13px; font-weight: 600; text-decoration: none; transition: all 0.2s; border: none; cursor: pointer; font-family: inherit; }\r\n");
      out.write("        .btn-primary { background: #1a73e8; color: #fff; }\r\n");
      out.write("        .btn-primary:hover { background: #1557b0; }\r\n");
      out.write("\r\n");
      out.write("        .card { background: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; margin-bottom: 20px; }\r\n");
      out.write("        .card-header { padding: 16px 20px; border-bottom: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; }\r\n");
      out.write("        .card-header h3 { font-size: 15px; font-weight: 600; color: #1e293b; display: flex; align-items: center; gap: 8px; }\r\n");
      out.write("        .card-header h3 i { color: #1a73e8; }\r\n");
      out.write("        .card-body { padding: 20px; }\r\n");
      out.write("\r\n");
      out.write("        .date-form { display: flex; gap: 12px; align-items: flex-end; flex-wrap: wrap; }\r\n");
      out.write("        .date-form .form-group { display: flex; flex-direction: column; gap: 6px; }\r\n");
      out.write("        .date-form .form-group label { font-size: 12px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }\r\n");
      out.write("        .form-control { padding: 9px 14px; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 14px; font-family: inherit; transition: border-color 0.2s; }\r\n");
      out.write("        .form-control:focus { outline: none; border-color: #1a73e8; box-shadow: 0 0 0 3px rgba(26,115,232,0.1); }\r\n");
      out.write("\r\n");
      out.write("        .alert { display: flex; align-items: center; gap: 10px; padding: 12px 16px; border-radius: 8px; margin-bottom: 20px; font-size: 14px; font-weight: 500; }\r\n");
      out.write("        .alert-error { background: #fef2f2; color: #dc2626; border: 1px solid #fecaca; }\r\n");
      out.write("        .alert-info { background: #e8f0fe; color: #1a73e8; border: 1px solid #bfdbfe; }\r\n");
      out.write("\r\n");
      out.write("        /* Groupe section - style simple */\r\n");
      out.write("        .groupe-section { margin-bottom: 32px; background: #fff; border-radius: 12px; border: 1px solid #e2e8f0; overflow: hidden; }\r\n");
      out.write("        .groupe-header { background: #f8fafc; padding: 16px 24px; border-bottom: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 12px; }\r\n");
      out.write("        .groupe-header .groupe-title { font-size: 16px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("        .groupe-header .groupe-info { display: flex; gap: 16px; font-size: 13px; color: #64748b; }\r\n");
      out.write("        .groupe-header .groupe-depart { background: #16a34a; color: #fff; padding: 4px 10px; border-radius: 4px; font-weight: 600; font-size: 12px; }\r\n");
      out.write("        .groupe-header .groupe-trigger { background: #0ea5e9; color: #fff; padding: 4px 10px; border-radius: 4px; font-weight: 600; font-size: 12px; }\r\n");
      out.write("        \r\n");
      out.write("        .groupe-content { padding: 16px 24px; }\r\n");
      out.write("\r\n");
      out.write("        /* Vehicle section */\r\n");
      out.write("        .vehicle-section { margin-bottom: 20px; border: 1px solid #e2e8f0; border-radius: 10px; overflow: hidden; }\r\n");
      out.write("        .vehicle-section:last-child { margin-bottom: 0; }\r\n");
      out.write("        .vehicle-header { background: #f8fafc; color: #334155; padding: 12px 20px; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px; border-bottom: 1px solid #e2e8f0; }\r\n");
      out.write("        .vehicle-header .vh-ref { font-size: 15px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("        .vehicle-header .vh-meta { display: flex; gap: 14px; font-size: 12px; color: #64748b; flex-wrap: wrap; }\r\n");
      out.write("        .vehicle-header .vh-count { font-size: 12px; color: #64748b; }\r\n");
      out.write("        .vehicle-header .vh-depart-mode { background: #f59e0b; color: #fff; padding: 4px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; }\r\n");
      out.write("\r\n");
      out.write("        .planning-table { width: 100%; border-collapse: collapse; background: #fff; }\r\n");
      out.write("        .planning-table thead th { padding: 10px 16px; font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; text-align: left; background: #f8fafc; border-bottom: 1px solid #e2e8f0; }\r\n");
      out.write("        .planning-table tbody td { padding: 10px 16px; font-size: 13px; color: #334155; border-bottom: 1px solid #f1f5f9; }\r\n");
      out.write("        .planning-table tbody tr:last-child td { border-bottom: none; }\r\n");
      out.write("\r\n");
      out.write("        .td-time { font-variant-numeric: tabular-nums; font-weight: 600; color: #1e293b; }\r\n");
      out.write("        .td-hotel { color: #1a73e8; font-weight: 600; }\r\n");
      out.write("        .td-ref { color: #64748b; }\r\n");
      out.write("\r\n");
      out.write("        .retour-row { background: #f0fdf4; padding: 10px 20px; display: flex; justify-content: space-between; align-items: center; }\r\n");
      out.write("        .retour-row .retour-label { font-size: 12px; font-weight: 600; color: #166534; }\r\n");
      out.write("        .retour-row .retour-time { font-size: 14px; font-weight: 700; color: #166534; }\r\n");
      out.write("\r\n");
      out.write("        .empty-state { text-align: center; padding: 60px 20px; }\r\n");
      out.write("        .empty-state i { font-size: 48px; color: #cbd5e1; margin-bottom: 16px; }\r\n");
      out.write("        .empty-state h2 { font-size: 20px; font-weight: 600; color: #475569; margin-bottom: 8px; }\r\n");
      out.write("        .empty-state p { color: #94a3b8; font-size: 14px; }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .sidebar { display: none; }\r\n");
      out.write("            .main { margin-left: 0; padding: 20px; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <aside class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-brand\">\r\n");
      out.write("            <i class=\"fas fa-building\"></i>\r\n");
      out.write("            <span>BackOffice <br>3341 -3256 -3326</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"sidebar-nav\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("                <i class=\"fas fa-home\"></i> Tableau de bord\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\">\r\n");
      out.write("                <i class=\"fas fa-calendar-check\"></i> Reservations\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vehicules\">\r\n");
      out.write("                <i class=\"fas fa-car\"></i> Vehicules\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotels\">\r\n");
      out.write("                <i class=\"fas fa-hotel\"></i> Hotels\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification\" class=\"active\">\r\n");
      out.write("                <i class=\"fas fa-route\"></i> Planification\r\n");
      out.write("            </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main\">\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <h1>Planification</h1>\r\n");
      out.write("            <p>Planning des vehicules pour les transferts - Regroupement par intervalle</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("                <h3><i class=\"fas fa-calendar-alt\"></i> Selectionner une date</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <form method=\"GET\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification\" class=\"date-form\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"date\">Date</label>\r\n");
      out.write("                        <input type=\"date\" id=\"date\" name=\"date\" class=\"form-control\"\r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dateSelectionnee != null ? dateSelectionnee : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-search\"></i> Afficher\r\n");
      out.write("                    </button>\r\n");
      out.write("                    ");
 if (request.getAttribute("dateSelectionnee") != null) { 
      out.write("\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification/vehicules-non-assignes?date=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dateSelectionnee}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                           class=\"btn btn-primary\" style=\"background:#16a34a; margin-left:8px;\">\r\n");
      out.write("                            <i class=\"fas fa-car\"></i> Véhicules non assignés\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification/reservations-non-assignees?date=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dateSelectionnee}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                           class=\"btn btn-primary\" style=\"background:#dc2626; margin-left:8px;\">\r\n");
      out.write("                            <i class=\"fas fa-exclamation-circle\"></i> Réservations non assignées\r\n");
      out.write("                        </a>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-error\">\r\n");
      out.write("                <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("                ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

        @SuppressWarnings("unchecked")
        List<Reservation> nonAssignees = (List<Reservation>) request.getAttribute("reservationsNonAssignees");
        if (nonAssignees != null && !nonAssignees.isEmpty()) {
        
      out.write("\r\n");
      out.write("            <div class=\"alert alert-error\" style=\"background: #fef2f2; border-left: 4px solid #dc2626; color: #991b1b;\">\r\n");
      out.write("                <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("                <strong>");
      out.print( nonAssignees.size() );
      out.write("</strong> réservation(s) n'ont pas pu être assignées.\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification/reservations-non-assignees?date=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dateSelectionnee}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                   style=\"margin-left: 10px; color: #dc2626; font-weight: bold;\">\r\n");
      out.write("                    Voir détails →\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

        @SuppressWarnings("unchecked")
        List<RegroupementDTO> regroupements = (List<RegroupementDTO>) request.getAttribute("regroupements");
        Integer totalVehicules = (Integer) request.getAttribute("totalVehicules");
        Integer delaiAttente = (Integer) request.getAttribute("delaiAttente");

        if (regroupements != null && !regroupements.isEmpty()) {
        
      out.write("\r\n");
      out.write("            <div class=\"alert alert-info\">\r\n");
      out.write("                <i class=\"fas fa-info-circle\"></i>\r\n");
      out.write("                Planning du <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dateSelectionnee}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong> &mdash; \r\n");
      out.write("                <strong>");
      out.print( regroupements.size() );
      out.write("</strong> groupe(s) | \r\n");
      out.write("                <strong>");
      out.print( totalVehicules );
      out.write("</strong> véhicule(s)\r\n");
      out.write("                <span style=\"margin-left: 16px; font-size: 12px; opacity: 0.8;\">\r\n");
      out.write("                    <i class=\"fas fa-clock\"></i> Délai d'attente : ");
      out.print( delaiAttente != null ? delaiAttente : 30 );
      out.write(" min\r\n");
      out.write("                </span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 for (RegroupementDTO groupe : regroupements) { 
      out.write("\r\n");
      out.write("                <div class=\"groupe-section\">\r\n");
      out.write("                    <div class=\"groupe-header\">\r\n");
      out.write("                        <span class=\"groupe-title\">Groupe ");
      out.print( groupe.getNumeroGroupe() );
      out.write("</span>\r\n");
      out.write("                        <div class=\"groupe-info\">\r\n");
      out.write("                            <span>Intervalle : ");
      out.print( groupe.getHeureDebut() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( groupe.getHeureFin() );
      out.write("</span>\r\n");
      out.write("                            <span>");
      out.print( groupe.getReservations().size() );
      out.write(" résa(s) | ");
      out.print( groupe.getNombrePersonnesTotal() );
      out.write(" pers | ");
      out.print( groupe.getVehiculesAssignes().size() );
      out.write(" véhicule(s)</span>\r\n");
      out.write("                            <span class=\"groupe-trigger\">Déclencheur : ");
      out.print( groupe.getTypeDeclencheurLabel() );
      out.write("</span>\r\n");
      out.write("                            <span class=\"groupe-depart\">DÉPART : ");
      out.print( groupe.getHeureDepart() );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"groupe-content\">\r\n");
      out.write("                        ");
 for (VehiculePlanningDTO vehiculePlanning : groupe.getVehiculesAssignes()) {
                            int totalPersonnes = vehiculePlanning.getNombrePassagers() != null ? 
                                vehiculePlanning.getNombrePassagers() : vehiculePlanning.calculerNombrePassagers();
                        
      out.write("\r\n");
      out.write("                            <div class=\"vehicle-section\">\r\n");
      out.write("                                <div class=\"vehicle-header\">\r\n");
      out.write("                                    <span class=\"vh-ref\">");
      out.print( vehiculePlanning.getVehicule().getReference() );
      out.write("</span>\r\n");
      out.write("                                    <div class=\"vh-meta\">\r\n");
      out.write("                                        <span>");
      out.print( vehiculePlanning.getVehicule().getPlace() );
      out.write(" pl (");
      out.print( totalPersonnes );
      out.write(" occ)</span>\r\n");
      out.write("                                        <span>");
      out.print( vehiculePlanning.getVehicule().getTypeCarburant().getLibelle() );
      out.write("</span>\r\n");
      out.write("                                        <span>");
      out.print( vehiculePlanning.getDestinationString() );
      out.write("</span>\r\n");
      out.write("                                        <span>");
      out.print( String.format("%.1f", vehiculePlanning.getDistanceTotale()) );
      out.write(" km</span>\r\n");
      out.write("                                        <span class=\"vh-depart-mode\">");
      out.print( vehiculePlanning.getModeDepartLabel() );
      out.write("</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <span class=\"vh-count\">");
      out.print( vehiculePlanning.getReservations().size() );
      out.write(" résa(s)</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <table class=\"planning-table\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>Ordre</th>\r\n");
      out.write("                                            <th>Référence</th>\r\n");
      out.write("                                            <th>Hôtel</th>\r\n");
      out.write("                                            <th>Client</th>\r\n");
      out.write("                                            <th>Personnes</th>\r\n");
      out.write("                                            <th>Heure RDV</th>\r\n");
      out.write("                                            <th>Départ segment</th>\r\n");
      out.write("                                            <th>Arrivée hôtel</th>\r\n");
      out.write("                                            <th>Distance</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                    ");
 int ordre = 1;
                                    for (ReservationPlanningDTO resPlanning : vehiculePlanning.getReservations()) { 
      out.write("\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>");
      out.print( ordre++ );
      out.write("</td>\r\n");
      out.write("                                            <td class=\"td-ref\">#");
      out.print( resPlanning.getReservation().getReference() );
      out.write("</td>\r\n");
      out.write("                                            <td class=\"td-hotel\">");
      out.print( resPlanning.getHotelLibelle() );
      out.write("</td>\r\n");
      out.write("                                            <td>");
      out.print( resPlanning.getReservation().getClient() != null ? resPlanning.getReservation().getClient() : "" );
      out.write("</td>\r\n");
      out.write("                                            <td>");
      out.print( resPlanning.getNombrePassagers() );
      out.write("</td>\r\n");
      out.write("                                            <td class=\"td-time\">");
      out.print( resPlanning.getReservation().getHeure() );
      out.write("</td>\r\n");
      out.write("                                            <td class=\"td-time\">");
      out.print( resPlanning.getHeureDepart() );
      out.write("</td>\r\n");
      out.write("                                            <td class=\"td-time\">");
      out.print( resPlanning.getHeureRetour() );
      out.write("</td>\r\n");
      out.write("                                            <td>");
      out.print( String.format("%.1f", resPlanning.getDistanceKm()) );
      out.write(" km</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"retour-row\">\r\n");
      out.write("                                    <span class=\"retour-label\"><i class=\"fas fa-plane-arrival\"></i> Retour à l'aéroport (TNR)</span>\r\n");
      out.write("                                    <span class=\"retour-time\">");
      out.print( vehiculePlanning.getHeureRetourAeroport() );
      out.write("</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } else if (request.getAttribute("dateSelectionnee") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"empty-state\">\r\n");
      out.write("                <i class=\"fas fa-calendar-times\"></i>\r\n");
      out.write("                <h2>Aucune réservation</h2>\r\n");
      out.write("                <p>Aucune réservation trouvée pour la date sélectionnée.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"empty-state\">\r\n");
      out.write("                <i class=\"fas fa-calendar-day\"></i>\r\n");
      out.write("                <h2>Sélectionnez une date</h2>\r\n");
      out.write("                <p>Veuillez sélectionner une date pour afficher le planning des véhicules.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
