/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-04-02 06:27:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.hotels;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.backoffice.models.Hotel;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.backoffice.models.Hotel");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hotels</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body { font-family: 'Inter', 'Segoe UI', sans-serif; background-color: #f0f4f8; min-height: 100vh; }\r\n");
      out.write("\r\n");
      out.write("        .sidebar { position: fixed; left: 0; top: 0; bottom: 0; width: 260px; background: #ffffff; border-right: 1px solid #e2e8f0; display: flex; flex-direction: column; z-index: 100; }\r\n");
      out.write("        .sidebar-brand { padding: 24px 20px; border-bottom: 1px solid #e2e8f0; display: flex; align-items: center; gap: 12px; }\r\n");
      out.write("        .sidebar-brand i { font-size: 24px; color: #1a73e8; }\r\n");
      out.write("        .sidebar-brand span { font-size: 18px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("        .sidebar-nav { padding: 16px 12px; flex: 1; }\r\n");
      out.write("        .sidebar-nav a { display: flex; align-items: center; gap: 12px; padding: 12px 16px; color: #64748b; text-decoration: none; border-radius: 8px; font-size: 14px; font-weight: 500; transition: all 0.2s; margin-bottom: 4px; }\r\n");
      out.write("        .sidebar-nav a:hover, .sidebar-nav a.active { background: #e8f0fe; color: #1a73e8; }\r\n");
      out.write("        .sidebar-nav a i { width: 20px; text-align: center; font-size: 16px; }\r\n");
      out.write("\r\n");
      out.write("        .main { margin-left: 260px; padding: 32px 40px; }\r\n");
      out.write("        .page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }\r\n");
      out.write("        .page-header h1 { font-size: 26px; font-weight: 700; color: #1e293b; }\r\n");
      out.write("\r\n");
      out.write("        .btn { display: inline-flex; align-items: center; gap: 8px; padding: 10px 20px; border-radius: 8px; font-size: 13px; font-weight: 600; text-decoration: none; transition: all 0.2s; border: none; cursor: pointer; }\r\n");
      out.write("        .btn-primary { background: #1a73e8; color: #fff; }\r\n");
      out.write("        .btn-primary:hover { background: #1557b0; }\r\n");
      out.write("        .btn-warning { background: #ea8600; color: #fff; }\r\n");
      out.write("        .btn-warning:hover { background: #d47a00; }\r\n");
      out.write("        .btn-danger { background: #ea4335; color: #fff; }\r\n");
      out.write("        .btn-danger:hover { background: #d33426; }\r\n");
      out.write("        .btn-sm { padding: 6px 14px; font-size: 12px; }\r\n");
      out.write("\r\n");
      out.write("        .message { display: flex; align-items: center; gap: 10px; padding: 12px 16px; background: #e6f4ea; color: #1e7e34; border-radius: 8px; margin-bottom: 20px; font-size: 14px; font-weight: 500; border: 1px solid #b7dfbf; }\r\n");
      out.write("        .message i { font-size: 16px; }\r\n");
      out.write("\r\n");
      out.write("        .stats-bar { display: flex; align-items: center; gap: 8px; margin-bottom: 16px; font-size: 14px; color: #64748b; }\r\n");
      out.write("        .stats-bar strong { color: #1a73e8; font-size: 18px; }\r\n");
      out.write("\r\n");
      out.write("        .card { background: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; margin-bottom: 20px; }\r\n");
      out.write("\r\n");
      out.write("        .data-table { width: 100%; border-collapse: collapse; }\r\n");
      out.write("        .data-table thead th { padding: 12px 16px; text-align: left; font-size: 12px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; background: #f8fafc; border-bottom: 2px solid #e2e8f0; }\r\n");
      out.write("        .data-table tbody td { padding: 14px 16px; font-size: 14px; color: #334155; border-bottom: 1px solid #f1f5f9; }\r\n");
      out.write("        .data-table tbody tr:hover { background: #f8fafc; }\r\n");
      out.write("        .data-table tbody tr:last-child td { border-bottom: none; }\r\n");
      out.write("        .actions-cell { display: flex; gap: 6px; }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .sidebar { display: none; }\r\n");
      out.write("            .main { margin-left: 0; padding: 20px; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <aside class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-brand\">\r\n");
      out.write("            <i class=\"fas fa-building\"></i>\r\n");
      out.write("            <span>BackOffice <br>3341 -3256 -3326</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"sidebar-nav\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("                <i class=\"fas fa-home\"></i> Tableau de bord\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\">\r\n");
      out.write("                <i class=\"fas fa-calendar-check\"></i> Reservations\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vehicules\">\r\n");
      out.write("                <i class=\"fas fa-car\"></i> Vehicules\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotels\" class=\"active\">\r\n");
      out.write("                <i class=\"fas fa-hotel\"></i> Hotels\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planification\">\r\n");
      out.write("                <i class=\"fas fa-route\"></i> Planification\r\n");
      out.write("            </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main\">\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <h1><i class=\"fas fa-hotel\" style=\"color:#1a73e8; margin-right:8px;\"></i> Hotels</h1>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotels/new\" class=\"btn btn-primary\">\r\n");
      out.write("                <i class=\"fas fa-plus\"></i> Nouvel hotel\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (request.getAttribute("message") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"message\">\r\n");
      out.write("                <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                ");
      out.print( request.getAttribute("message") );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

            List<Hotel> hotels = (List<Hotel>) request.getAttribute("hotels");
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"stats-bar\">\r\n");
      out.write("            <i class=\"fas fa-list\" style=\"color:#1a73e8;\"></i>\r\n");
      out.write("            <strong>");
      out.print( hotels != null ? hotels.size() : 0 );
      out.write("</strong> hotel(s)\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <table class=\"data-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ID</th>\r\n");
      out.write("                        <th>Libelle</th>\r\n");
      out.write("                        <th>Actions</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");

                        if (hotels != null) {
                            for (Hotel h : hotels) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( h.getId() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( h.getLibelle() );
      out.write("</td>\r\n");
      out.write("                        <td class=\"actions-cell\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotels/edit?id=");
      out.print( h.getId() );
      out.write("\" class=\"btn btn-warning btn-sm\">\r\n");
      out.write("                                <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotels/delete?id=");
      out.print( h.getId() );
      out.write("\" class=\"btn btn-danger btn-sm\" onclick=\"return confirm('Supprimer cet hotel ?');\">\r\n");
      out.write("                                <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
